export enum OrderStatus {
  PENDING = 'PENDING',
  ON_HOLD = 'ON_HOLD',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
  EXCHANGED = 'EXCHANGED',
  REFUNDED = 'REFUNDED',
  ISSUE_RAISED = 'ISSUE_RAISED',
}
