export enum PaymentMethod {
  CASH = 'CASH',
  BKASH = 'BKASH',
  NAGAD = 'NAGAD',
  ROCKET = 'ROCKET',
  BANK_TRANSFER = 'BANK_TRANSFER',
  DISCOUNT_COUPON = 'DISCOUNT_COUPON',
  SPECIAL_EXCEPTION = 'SPECIAL_EXCEPTION',
  OTHER = 'OTHER',
}
