export enum ReturnReason {
  FAULTY = 'FAULTY',
  WRONG_PRODUCT = 'WRONG_PRODUCT',
  USER_DID_NOT_LIKE = 'USER_DID_NOT_LIKE',
  DAMAGED = 'DAMAGED',
  COURIER_ISSUE = 'COURIER_ISSUE',
  OTHER = 'OTHER',
}
